apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: add-ons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucasafonsokremer/k8s-setup-argocd-controlplane.git
    targetRevision: HEAD
    path: charts/controlplane-add-ons
    helm:
      release: add-ons
      values: |
        ingress-nginx:
          enable: true
        metrics-server:
          enable: true  
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: argocd