# Global Values
repoUrl: 'https://github.com/lucasafonsokremer/k8s-setup-argocd-controlplane.git'
targetRevision: HEAD
region: ''
account: ''
clusterName: ''
destinationServer: ''
argoNamespace: ''
argoProject: ''

# Nginx Values
ingressNginx:
  enable: false
  createNamespace: true

# Metrics Server Values
metricsServer:
  enable: false